services:
  - type: web
    name: resort-booking
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn resort.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0